hero-mobile
Falconoff/hell-eng pull request #24
Opened 2021-07-05 19:00 UTC by dimatytenko

убрал лишние маржины

2021-07-05 19:51 UTC, Falconoff requested changes
надо исправить

2021-07-05 19:51 UTC, Falconoff commented on src/partials/hero.html
>      <h1 class="hero__title">Complex preparation for English UPE</h1>
< h1 class="section__title hero__title"> - надо 2 названия классов, потому что стили я добавил для .section__title в общем файле и они совпадают с этим заголовком на мобилке и планшете, а вот для десктопа в макете побольше размер шрифта, для этого пропишешь уже в .hero__title размер font-size

2021-07-05 19:51 UTC, Falconoff commented on src/partials/hero.html
>      <button class="hero__button" type="button">
Не, так вообще нельзя: надо использовать либо тег button, либо <a>, а вместе они не используются.
Ссылки используются когда надо куда-то перейти (на другую страницу или сайт), а кнопки - когда надо что-то сделать на текущей странице, даже без перезагрузки её.
В ТЗ написано "Кнопка “Хочу на бесплатное занятие” является якорной **_ссылкой_** на раздел с формой." Поэтому удали баттон вообще, а ссылке как раз и дай класс hero__button

2021-07-06 13:06 UTC, dimatytenko commented on src/partials/hero.html
>      <h1 class="hero__title">Complex preparation for English UPE</h1>
стили для title потом поменяю, класса мне пока небыло видно.

2021-07-06 13:06 UTC, dimatytenko commented on src/partials/hero.html
>      <button class="hero__button" type="button">
Исправил.

2021-07-06 13:11 UTC, Falconoff approved these changes

2021-07-06 13:11 UTC, merged