second save
Falconoff/hell-eng pull request #35
Opened 2021-07-06 16:26 UTC by Gerodot21

2021-07-06 20:15 UTC, Falconoff requested changes

2021-07-06 20:15 UTC, Falconoff commented on src/partials/problems.html
> +<section class="container problems section">
ну ты понял) секция с классом секция, в ней див с классом контейнер и т.д. ))

2021-07-06 20:15 UTC, Falconoff commented on src/partials/problems.html
> +  <h3 class="section__title section__title--white problems__title">
исправь тег h3 на h2. У тебя же нет нигде 2? А 3 должна идти только если есть уже 2

2021-07-07 07:48 UTC, Gerodot21 reviewed
problems and benefits

2021-07-07 11:32 UTC, Alexilch approved these changes

2021-07-07 11:52 UTC, closed without merging